name: CICD (Dev, UAT)

on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md

  workflow_dispatch:

jobs:

  dev:
    uses: ./.github/workflows/workflow.yml
    with:
      environment: dev
      module: network
    secrets: inherit

  uat:
    needs: [dev]
    uses: ./.github/workflows/workflow.yml
    with:
      environment: uat
      module: network
    secrets: inherit    