name: CICD (Dev, UAT)

on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md

  workflow_dispatch:

jobs:

  build:
    uses: ./.github/workflows/workflow.yml
    with:
      environment: dev
      module: network
    secrets: inherit